### ISSUE TITLE
[meta] Merge repo into web-platform-tests

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1102]
From <https://lists.w3.org/Archives/Public/www-style/2016Oct/0088.html>:

- [x] Land https://github.com/w3c/wpt-tools/pull/90 into wpt-tools so that the web-platform-tests tools create an accurate manifest (i.e., list of tests) for the CSS testsuite.
- [x] Add a number of lints to wpt-tools, for the (currently non-existent) css subdirectory, to ensure that the build system keeps working (primarily we need lints to ensure that we have no duplicate file-extensionless-basenames that aren't byte-for-byte identical and that all files referenced by test files are in an adjacent support or reference directory, with a couple of exceptions).
- [x] Ensure web-platform-tests's documentation is up-to-date and cohesive, both for submitting tests and reviewing them. Especially make sure it's easier to find documentation than it is currently!
- [x] Make https://hg.csswg.org/test/ and http://test.csswg.org/shepherd/ read-only. (This only depends on making sure we have something in way of GitHub documentation; #1101 )
- [x] Merge csswg-test into web-platform-tests, in a css/ subdirectory, maintaining all csswg-test history, with w3ctestlib and apiclient being moved over to git submodules.
- [ ] Move over, at the very least, all open issues and PRs from the csswg-test repository.
- [ ] (Sometime in the more distant future) drop the current build system and the lints we had for its requirements.

**Comment by gsnedders** [comment]
The merge itself is now done. WOOOOO.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5486; please continue all discussion there.
